spring:
  application:
    name: notification-server


  kafka:
    bootstrap-servers: 34.71.194.186:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: notification-server
      auto-offset-reset: earliest

  datasource:
    url: jdbc:mysql://localhost:3306/notification?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update